# Generated by Django 3.1.3 on 2020-11-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contestant',
                'verbose_name_plural': 'Contestants',
                'db_table': 'Contestants_Info',
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('voted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.contestants')),
            ],
            options={
                'verbose_name': 'Voter',
                'verbose_name_plural': 'Voters',
                'db_table': 'Voters_Info',
            },
        ),
    ]
