# Generated by Django 3.1.3 on 2020-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20201120_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='vote',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
