# Generated by Django 3.1.3 on 2020-11-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20201120_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
