# Generated by Django 3.1 on 2020-11-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_auto_20201120_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='email',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
